### ISSUE TITLE
Add RSS feed to the mailing list

### ISSUE THREAD

**Issue by mattiasgeniar** [mattiasgeniar/CommunityBitcoin#1]
- new topics
- new messages in existing topics

**Comment by freekmurze** [comment]
So there should be one RSS feed with all messages across all topics, and then a feed per topic with all messages of that topic, right?

**Comment by mattiasgeniar** [comment]
That sounds useful yes, it allows anyone to follow a particular thread (if they're interested) and be notified of new topics being posted.

**Comment by mattiasgeniar** [comment]
Thanks @freekmurze !
