### ISSUE TITLE
Add pagination to the thread & messages list

### ISSUE THREAD

**Issue by mattiasgeniar** [mattiasgeniar/CommunityBitcoin#4]
Ie here:
- https://mojah.be/mailing-list/author/1
- https://mojah.be/mailing-list/bitcoin-dev

**Comment by mattiasgeniar** [comment]
Thanks for the feature @ijpatricio !

**Comment by ijpatricio** [comment]
Glad you liked it @mattiasgeniar !

Now someone with design skills can style it further!
